apiVersion: v1
kind: Pod
metadata:
  name: nmap
  labels:
    app: nmap
spec:
  containers:
  - name: nmap
    image: instrumentisto/nmap
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"] #NEED TO KEEP POD RUNNING
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
